import React from 'react';
import CustomNode from './CustomNode';

export const graphHeight = window.innerHeight;
export const graphWidth = window.innerWidth;

export const graphConfig = {
  automaticRearrangeAfterDropNode: true,
  collapsible: false,
  directed: false,
  focusAnimationDuration: 0.75,
  focusZoom: 1,
  height: graphHeight,
  highlightDegree: 1,
  highlightOpacity: 0.2,
  linkHighlightBehavior: false,
  maxZoom: 8,
  minZoom: 0.1,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  staticGraphWithDragAndDrop: false,
  width: graphWidth,
  d3: {
    alphaTarget: 0.05,
    gravity: -2000,
    linkLength: 300,
    linkStrength: 1,
    disableLinkForce: false,
  },
  node: {
    color: '#d3d3d3',
    fontColor: 'black',
    fontSize: 16,
    fontWeight: 'normal',
    highlightColor: '#00e676',
    highlightFontSize: 16,
    highlightFontWeight: 'bold',
    highlightStrokeColor: 'SAME',
    highlightStrokeWidth: 1.5,
    labelPosition: 'right',
    mouseCursor: 'pointer',
    opacity: 1,
    renderLabel: false,
    size: 1000,
    strokeColor: 'none',
    strokeWidth: 1.5,
    svg: '',
    symbolType: 'circle',
    viewGenerator: (node) => <CustomNode artist={node} />,
  },
  link: {
    color: '#d3d3d3',
    fontColor: 'red',
    fontSize: 10,
    fontWeight: 'normal',
    highlightColor: '#00e676',
    highlightFontSize: 8,
    highlightFontWeight: 'bold',
    mouseCursor: 'auto',
    opacity: 1,
    renderLabel: false,
    semanticStrokeWidth: false,
    strokeWidth: 6,
    markerHeight: 6,
    markerWidth: 6,
  },
};
